# Generated by Django 5.1.1 on 2024-09-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('air_date', models.CharField()),
                ('episode', models.CharField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('dimension', models.CharField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('unknown', 'unknown')])),
                ('species', models.CharField()),
                ('type', models.CharField()),
                ('image', models.CharField()),
                ('episode', models.ManyToManyField(to='rym.episode')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rym.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='rym.location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
