# Generated by Django 5.1.1 on 2024-09-11 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless'), ('unknown', 'unknown')], default='unknown'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rym.location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='rym.location'),
        ),
    ]
