# Generated by Django 5.1.1 on 2024-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0002_character_gender_location_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/locations/'),
        ),
    ]
