# Generated by Django 5.1.1 on 2024-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0003_alter_character_location_alter_character_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless'), ('unknown', 'unknown')], default='unknown'),
        ),
    ]
