# Generated by Django 5.1.1 on 2024-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0004_character_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(),
        ),
    ]
