# Generated by Django 5.1.1 on 2024-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0005_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
