# Generated by Django 5.1.1 on 2024-09-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0006_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
