# Generated by Django 5.1.1 on 2024-09-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rym', '0007_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
